CREATE TABLE IF NOT EXISTS "professions" (
	"id"	INTEGER NOT NULL UNIQUE,
	"profession"	TEXT NOT NULL UNIQUE,
	"Pa"	NUMERIC NOT NULL,
	"p1(x/w)"	NUMERIC,
	"p1(x/now)"	NUMERIC,
	"p2(x/w)"	NUMERIC,
	"p2(x/now)"	NUMERIC,
	"p3(x/w)"	NUMERIC,
	"p3(x/now)"	NUMERIC,
	"p4(x/w)"	NUMERIC,
	"p4(x/now)"	NUMERIC,
	"p5(x/w)"	NUMERIC,
	"p5(x/now)"	NUMERIC,
	"p6(x/w)"	NUMERIC,
	"p6(x/now)"	NUMERIC,
	"p7(x/w)"	NUMERIC,
	"p7(x/now)"	NUMERIC,
	"p8(x/w)"	NUMERIC,
	"p8(x/now)"	NUMERIC,
	"p9(x/w)"	NUMERIC,
	"p9(x/now)"	NUMERIC,
	"p10(x/w)"	NUMERIC,
	"p10(x/now)"	NUMERIC,
	"p11(x/w)"	NUMERIC,
	"p11(x/now)"	NUMERIC,
	"p12(x/w)"	NUMERIC,
	"p12(x/now)"	NUMERIC,
	"p13(x/w)"	NUMERIC,
	"p13(x/now)"	NUMERIC,
	"p14(x/w)"	NUMERIC,
	"p14(x/now)"	NUMERIC,
	"p15(x/w)"	NUMERIC,
	"p15(x/now)"	NUMERIC,
	PRIMARY KEY("id" AUTOINCREMENT)
);